# Supported Star Fox 64 Versions: US

f7475fb11e7e6830f82883412638e8390791ab87:
  name: Star Fox 64 (U) (V1.1)
  path: assets/yaml/us
  config:
    gbi: F3DEX
    sort: OFFSET
    output:
      binary: lylat.otr
      code: src/assets
      headers: include/assets
      modding: src/assets
    enums:
      - include/sf64object.h